twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'forms/jquery.collection.html.twig'
        - 'forms/widgets/favorite_movie_widget.html.twig'
