#controllers:
#    resource: ../../src/Controller/
#    type: annotation

base:
    resource: ../../src/Controller/_config/routes.yaml

kernel:
    resource: ../../src/Kernel.php
    type: annotation
